//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheMinx.wsTabAuth {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.thirdparty.api.neo.tabcorp.com.au/")]
    public partial class APIException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageDetailField;
        
        private string errorTypeField;
        
        private string messageMapField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string messageDetail {
            get {
                return this.messageDetailField;
            }
            set {
                this.messageDetailField = value;
                this.RaisePropertyChanged("messageDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string errorType {
            get {
                return this.errorTypeField;
            }
            set {
                this.errorTypeField = value;
                this.RaisePropertyChanged("errorType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string messageMap {
            get {
                return this.messageMapField;
            }
            set {
                this.messageMapField = value;
                this.RaisePropertyChanged("messageMap");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.thirdparty.api.neo.tabcorp.com.au/")]
    public partial class thirdPartyCustomerAuthenticateResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double accountBalanceField;
        
        private long accountIdField;
        
        private string emailIdField;
        
        private string firstNameField;
        
        private long jurisdictionIdField;
        
        private bool jurisdictionIdFieldSpecified;
        
        private string lastNameField;
        
        private int tierCodeField;
        
        private string usernamePasswordTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double accountBalance {
            get {
                return this.accountBalanceField;
            }
            set {
                this.accountBalanceField = value;
                this.RaisePropertyChanged("accountBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long accountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
                this.RaisePropertyChanged("accountId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string emailId {
            get {
                return this.emailIdField;
            }
            set {
                this.emailIdField = value;
                this.RaisePropertyChanged("emailId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("firstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long jurisdictionId {
            get {
                return this.jurisdictionIdField;
            }
            set {
                this.jurisdictionIdField = value;
                this.RaisePropertyChanged("jurisdictionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool jurisdictionIdSpecified {
            get {
                return this.jurisdictionIdFieldSpecified;
            }
            set {
                this.jurisdictionIdFieldSpecified = value;
                this.RaisePropertyChanged("jurisdictionIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int tierCode {
            get {
                return this.tierCodeField;
            }
            set {
                this.tierCodeField = value;
                this.RaisePropertyChanged("tierCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string usernamePasswordToken {
            get {
                return this.usernamePasswordTokenField;
            }
            set {
                this.usernamePasswordTokenField = value;
                this.RaisePropertyChanged("usernamePasswordToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.thirdparty.api.neo.tabcorp.com.au/")]
    public partial class thirdPartyCustomerAuthenticateRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long accountIdField;
        
        private string accountPasswordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long accountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
                this.RaisePropertyChanged("accountId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string accountPassword {
            get {
                return this.accountPasswordField;
            }
            set {
                this.accountPasswordField = value;
                this.RaisePropertyChanged("accountPassword");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.thirdparty.api.neo.tabcorp.com.au/")]
    public partial class apiMeta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long deviceIdField;
        
        private bool deviceIdFieldSpecified;
        
        private long jurisdictionIdField;
        
        private long requestChannelField;
        
        private bool requestChannelFieldSpecified;
        
        private string usernamePasswordTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
                this.RaisePropertyChanged("deviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deviceIdSpecified {
            get {
                return this.deviceIdFieldSpecified;
            }
            set {
                this.deviceIdFieldSpecified = value;
                this.RaisePropertyChanged("deviceIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long jurisdictionId {
            get {
                return this.jurisdictionIdField;
            }
            set {
                this.jurisdictionIdField = value;
                this.RaisePropertyChanged("jurisdictionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long requestChannel {
            get {
                return this.requestChannelField;
            }
            set {
                this.requestChannelField = value;
                this.RaisePropertyChanged("requestChannel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requestChannelSpecified {
            get {
                return this.requestChannelFieldSpecified;
            }
            set {
                this.requestChannelFieldSpecified = value;
                this.RaisePropertyChanged("requestChannelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string usernamePasswordToken {
            get {
                return this.usernamePasswordTokenField;
            }
            set {
                this.usernamePasswordTokenField = value;
                this.RaisePropertyChanged("usernamePasswordToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.thirdparty.api.neo.tabcorp.com.au/", ConfigurationName="wsTabAuth.ThirdPartyCustomerAuthenticateService")]
    public interface ThirdPartyCustomerAuthenticateService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TheMinx.wsTabAuth.APIException), Action="", Name="APIException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TheMinx.wsTabAuth.authenticateAccountResponse authenticateAccount(TheMinx.wsTabAuth.authenticateAccount request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TheMinx.wsTabAuth.authenticateAccountResponse> authenticateAccountAsync(TheMinx.wsTabAuth.authenticateAccount request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authenticateAccount", WrapperNamespace="http://service.thirdparty.api.neo.tabcorp.com.au/", IsWrapped=true)]
    public partial class authenticateAccount {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.thirdparty.api.neo.tabcorp.com.au/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TheMinx.wsTabAuth.apiMeta apiMeta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.thirdparty.api.neo.tabcorp.com.au/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TheMinx.wsTabAuth.thirdPartyCustomerAuthenticateRequest authRequest;
        
        public authenticateAccount() {
        }
        
        public authenticateAccount(TheMinx.wsTabAuth.apiMeta apiMeta, TheMinx.wsTabAuth.thirdPartyCustomerAuthenticateRequest authRequest) {
            this.apiMeta = apiMeta;
            this.authRequest = authRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authenticateAccountResponse", WrapperNamespace="http://service.thirdparty.api.neo.tabcorp.com.au/", IsWrapped=true)]
    public partial class authenticateAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.thirdparty.api.neo.tabcorp.com.au/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TheMinx.wsTabAuth.thirdPartyCustomerAuthenticateResponse @return;
        
        public authenticateAccountResponse() {
        }
        
        public authenticateAccountResponse(TheMinx.wsTabAuth.thirdPartyCustomerAuthenticateResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ThirdPartyCustomerAuthenticateServiceChannel : TheMinx.wsTabAuth.ThirdPartyCustomerAuthenticateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ThirdPartyCustomerAuthenticateServiceClient : System.ServiceModel.ClientBase<TheMinx.wsTabAuth.ThirdPartyCustomerAuthenticateService>, TheMinx.wsTabAuth.ThirdPartyCustomerAuthenticateService {
        
        public ThirdPartyCustomerAuthenticateServiceClient() {
        }
        
        public ThirdPartyCustomerAuthenticateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ThirdPartyCustomerAuthenticateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThirdPartyCustomerAuthenticateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThirdPartyCustomerAuthenticateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TheMinx.wsTabAuth.authenticateAccountResponse TheMinx.wsTabAuth.ThirdPartyCustomerAuthenticateService.authenticateAccount(TheMinx.wsTabAuth.authenticateAccount request) {
            return base.Channel.authenticateAccount(request);
        }
        
        public TheMinx.wsTabAuth.thirdPartyCustomerAuthenticateResponse authenticateAccount(TheMinx.wsTabAuth.apiMeta apiMeta, TheMinx.wsTabAuth.thirdPartyCustomerAuthenticateRequest authRequest) {
            TheMinx.wsTabAuth.authenticateAccount inValue = new TheMinx.wsTabAuth.authenticateAccount();
            inValue.apiMeta = apiMeta;
            inValue.authRequest = authRequest;
            TheMinx.wsTabAuth.authenticateAccountResponse retVal = ((TheMinx.wsTabAuth.ThirdPartyCustomerAuthenticateService)(this)).authenticateAccount(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TheMinx.wsTabAuth.authenticateAccountResponse> TheMinx.wsTabAuth.ThirdPartyCustomerAuthenticateService.authenticateAccountAsync(TheMinx.wsTabAuth.authenticateAccount request) {
            return base.Channel.authenticateAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<TheMinx.wsTabAuth.authenticateAccountResponse> authenticateAccountAsync(TheMinx.wsTabAuth.apiMeta apiMeta, TheMinx.wsTabAuth.thirdPartyCustomerAuthenticateRequest authRequest) {
            TheMinx.wsTabAuth.authenticateAccount inValue = new TheMinx.wsTabAuth.authenticateAccount();
            inValue.apiMeta = apiMeta;
            inValue.authRequest = authRequest;
            return ((TheMinx.wsTabAuth.ThirdPartyCustomerAuthenticateService)(this)).authenticateAccountAsync(inValue);
        }
    }
}
