//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheMinx.wsTabBetting {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/")]
    public partial class APIException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageDetailField;
        
        private string errorTypeField;
        
        private string messageMapField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string messageDetail {
            get {
                return this.messageDetailField;
            }
            set {
                this.messageDetailField = value;
                this.RaisePropertyChanged("messageDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string errorType {
            get {
                return this.errorTypeField;
            }
            set {
                this.errorTypeField = value;
                this.RaisePropertyChanged("errorType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string messageMap {
            get {
                return this.messageMapField;
            }
            set {
                this.messageMapField = value;
                this.RaisePropertyChanged("messageMap");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/")]
    public partial class multiParlayContent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long multiParlayCombinationsField;
        
        private string multiParlayFormulaField;
        
        private double multiParlayPayoutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long multiParlayCombinations {
            get {
                return this.multiParlayCombinationsField;
            }
            set {
                this.multiParlayCombinationsField = value;
                this.RaisePropertyChanged("multiParlayCombinations");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string multiParlayFormula {
            get {
                return this.multiParlayFormulaField;
            }
            set {
                this.multiParlayFormulaField = value;
                this.RaisePropertyChanged("multiParlayFormula");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double multiParlayPayout {
            get {
                return this.multiParlayPayoutField;
            }
            set {
                this.multiParlayPayoutField = value;
                this.RaisePropertyChanged("multiParlayPayout");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/")]
    public partial class flexiResp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long betNumberField;
        
        private bool betNumberFieldSpecified;
        
        private double payoutPercentField;
        
        private long percentBetComboField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long betNumber {
            get {
                return this.betNumberField;
            }
            set {
                this.betNumberField = value;
                this.RaisePropertyChanged("betNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool betNumberSpecified {
            get {
                return this.betNumberFieldSpecified;
            }
            set {
                this.betNumberFieldSpecified = value;
                this.RaisePropertyChanged("betNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double payoutPercent {
            get {
                return this.payoutPercentField;
            }
            set {
                this.payoutPercentField = value;
                this.RaisePropertyChanged("payoutPercent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long percentBetCombo {
            get {
                return this.percentBetComboField;
            }
            set {
                this.percentBetComboField = value;
                this.RaisePropertyChanged("percentBetCombo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/")]
    public partial class sportsPayoutResp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string projectedPayoutField;
        
        private string sportsBetNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string projectedPayout {
            get {
                return this.projectedPayoutField;
            }
            set {
                this.projectedPayoutField = value;
                this.RaisePropertyChanged("projectedPayout");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string sportsBetNumber {
            get {
                return this.sportsBetNumberField;
            }
            set {
                this.sportsBetNumberField = value;
                this.RaisePropertyChanged("sportsBetNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/")]
    public partial class legDetailsResp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime eventDateField;
        
        private bool eventDateFieldSpecified;
        
        private string eventNameField;
        
        private string legStatusField;
        
        private int prodCodeField;
        
        private bool prodCodeFieldSpecified;
        
        private string propositionNameField;
        
        private long propositionNumberField;
        
        private string raceNameField;
        
        private int raceNumberField;
        
        private System.DateTime raceStartTimeField;
        
        private bool raceStartTimeFieldSpecified;
        
        private betSelection[] selectionListField;
        
        private sportsPayoutResp[] sportsPayoutListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime eventDate {
            get {
                return this.eventDateField;
            }
            set {
                this.eventDateField = value;
                this.RaisePropertyChanged("eventDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventDateSpecified {
            get {
                return this.eventDateFieldSpecified;
            }
            set {
                this.eventDateFieldSpecified = value;
                this.RaisePropertyChanged("eventDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string eventName {
            get {
                return this.eventNameField;
            }
            set {
                this.eventNameField = value;
                this.RaisePropertyChanged("eventName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string legStatus {
            get {
                return this.legStatusField;
            }
            set {
                this.legStatusField = value;
                this.RaisePropertyChanged("legStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int prodCode {
            get {
                return this.prodCodeField;
            }
            set {
                this.prodCodeField = value;
                this.RaisePropertyChanged("prodCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prodCodeSpecified {
            get {
                return this.prodCodeFieldSpecified;
            }
            set {
                this.prodCodeFieldSpecified = value;
                this.RaisePropertyChanged("prodCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string propositionName {
            get {
                return this.propositionNameField;
            }
            set {
                this.propositionNameField = value;
                this.RaisePropertyChanged("propositionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long propositionNumber {
            get {
                return this.propositionNumberField;
            }
            set {
                this.propositionNumberField = value;
                this.RaisePropertyChanged("propositionNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string raceName {
            get {
                return this.raceNameField;
            }
            set {
                this.raceNameField = value;
                this.RaisePropertyChanged("raceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int raceNumber {
            get {
                return this.raceNumberField;
            }
            set {
                this.raceNumberField = value;
                this.RaisePropertyChanged("raceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public System.DateTime raceStartTime {
            get {
                return this.raceStartTimeField;
            }
            set {
                this.raceStartTimeField = value;
                this.RaisePropertyChanged("raceStartTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool raceStartTimeSpecified {
            get {
                return this.raceStartTimeFieldSpecified;
            }
            set {
                this.raceStartTimeFieldSpecified = value;
                this.RaisePropertyChanged("raceStartTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("selectionList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public betSelection[] selectionList {
            get {
                return this.selectionListField;
            }
            set {
                this.selectionListField = value;
                this.RaisePropertyChanged("selectionList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sportsPayoutList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public sportsPayoutResp[] sportsPayoutList {
            get {
                return this.sportsPayoutListField;
            }
            set {
                this.sportsPayoutListField = value;
                this.RaisePropertyChanged("sportsPayoutList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/")]
    public partial class betSelection : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string selectionNameField;
        
        private string selectionNumberField;
        
        private string selectionSeparatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string selectionName {
            get {
                return this.selectionNameField;
            }
            set {
                this.selectionNameField = value;
                this.RaisePropertyChanged("selectionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string selectionNumber {
            get {
                return this.selectionNumberField;
            }
            set {
                this.selectionNumberField = value;
                this.RaisePropertyChanged("selectionNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string selectionSeparator {
            get {
                return this.selectionSeparatorField;
            }
            set {
                this.selectionSeparatorField = value;
                this.RaisePropertyChanged("selectionSeparator");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/")]
    public partial class deductDetailsResp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double amountPlaceDeductField;
        
        private double amountWinDeductField;
        
        private string deductDurationField;
        
        private System.Nullable<long>[] scratchListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double amountPlaceDeduct {
            get {
                return this.amountPlaceDeductField;
            }
            set {
                this.amountPlaceDeductField = value;
                this.RaisePropertyChanged("amountPlaceDeduct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double amountWinDeduct {
            get {
                return this.amountWinDeductField;
            }
            set {
                this.amountWinDeductField = value;
                this.RaisePropertyChanged("amountWinDeduct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string deductDuration {
            get {
                return this.deductDurationField;
            }
            set {
                this.deductDurationField = value;
                this.RaisePropertyChanged("deductDuration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("scratchList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public System.Nullable<long>[] scratchList {
            get {
                return this.scratchListField;
            }
            set {
                this.scratchListField = value;
                this.RaisePropertyChanged("scratchList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/")]
    public partial class comboBetContent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string allUpFormulaField;
        
        private System.Nullable<double>[] amountInvestedListField;
        
        private double betCostAmountField;
        
        private bool betCostAmountFieldSpecified;
        
        private int scheduledTypeField;
        
        private deductDetailsResp[] deductDetailsListField;
        
        private legDetailsResp[] legListField;
        
        private System.DateTime meetingDateField;
        
        private bool meetingDateFieldSpecified;
        
        private string overallPayoutField;
        
        private int overallStatusField;
        
        private string returnsOverallField;
        
        private int meetingCodeField;
        
        private bool meetingCodeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string allUpFormula {
            get {
                return this.allUpFormulaField;
            }
            set {
                this.allUpFormulaField = value;
                this.RaisePropertyChanged("allUpFormula");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("amountInvestedList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<double>[] amountInvestedList {
            get {
                return this.amountInvestedListField;
            }
            set {
                this.amountInvestedListField = value;
                this.RaisePropertyChanged("amountInvestedList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double betCostAmount {
            get {
                return this.betCostAmountField;
            }
            set {
                this.betCostAmountField = value;
                this.RaisePropertyChanged("betCostAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool betCostAmountSpecified {
            get {
                return this.betCostAmountFieldSpecified;
            }
            set {
                this.betCostAmountFieldSpecified = value;
                this.RaisePropertyChanged("betCostAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int scheduledType {
            get {
                return this.scheduledTypeField;
            }
            set {
                this.scheduledTypeField = value;
                this.RaisePropertyChanged("scheduledType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deductDetailsList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public deductDetailsResp[] deductDetailsList {
            get {
                return this.deductDetailsListField;
            }
            set {
                this.deductDetailsListField = value;
                this.RaisePropertyChanged("deductDetailsList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("legList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public legDetailsResp[] legList {
            get {
                return this.legListField;
            }
            set {
                this.legListField = value;
                this.RaisePropertyChanged("legList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime meetingDate {
            get {
                return this.meetingDateField;
            }
            set {
                this.meetingDateField = value;
                this.RaisePropertyChanged("meetingDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool meetingDateSpecified {
            get {
                return this.meetingDateFieldSpecified;
            }
            set {
                this.meetingDateFieldSpecified = value;
                this.RaisePropertyChanged("meetingDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string overallPayout {
            get {
                return this.overallPayoutField;
            }
            set {
                this.overallPayoutField = value;
                this.RaisePropertyChanged("overallPayout");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int overallStatus {
            get {
                return this.overallStatusField;
            }
            set {
                this.overallStatusField = value;
                this.RaisePropertyChanged("overallStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string returnsOverall {
            get {
                return this.returnsOverallField;
            }
            set {
                this.returnsOverallField = value;
                this.RaisePropertyChanged("returnsOverall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int meetingCode {
            get {
                return this.meetingCodeField;
            }
            set {
                this.meetingCodeField = value;
                this.RaisePropertyChanged("meetingCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool meetingCodeSpecified {
            get {
                return this.meetingCodeFieldSpecified;
            }
            set {
                this.meetingCodeFieldSpecified = value;
                this.RaisePropertyChanged("meetingCodeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/")]
    public partial class betDetailsResp : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long acceptTimerField;
        
        private bool acceptTimerFieldSpecified;
        
        private double accountBalanceField;
        
        private bool accountBalanceFieldSpecified;
        
        private string allUpFormulaField;
        
        private double amountCreditBalanceField;
        
        private bool amountCreditBalanceFieldSpecified;
        
        private System.Nullable<double>[] amountInvestedListField;
        
        private double amountSessionBalanceField;
        
        private bool amountSessionBalanceFieldSpecified;
        
        private double amountTicketField;
        
        private bool amountTicketFieldSpecified;
        
        private double amountWithdrawField;
        
        private double betCostAmountField;
        
        private bool betCostAmountFieldSpecified;
        
        private long betRefIdField;
        
        private System.DateTime betSoldTimeField;
        
        private bool betSoldTimeFieldSpecified;
        
        private comboBetContent[] comboBetContentField;
        
        private int scheduledTypeField;
        
        private string counterOfferPayoutField;
        
        private string counterOfferReturnField;
        
        private string counterOfferTakeField;
        
        private deductDetailsResp[] deductDetailsListField;
        
        private bool flexiBetField;
        
        private flexiResp[] flexiListField;
        
        private legDetailsResp[] legListField;
        
        private System.DateTime meetingDateField;
        
        private bool meetingDateFieldSpecified;
        
        private string meetingLocationField;
        
        private string meetingNameField;
        
        private multiParlayContent[] multiParlayContentListField;
        
        private bool mysteryField;
        
        private double openBalanceField;
        
        private bool openBalanceFieldSpecified;
        
        private string overAllPayoutField;
        
        private int overallStatusField;
        
        private int promotionFlagField;
        
        private string returnsOverallField;
        
        private string statusCodeField;
        
        private string statusMessageField;
        
        private string statusTypeField;
        
        private string transactionNumberField;
        
        private int meetingCodeField;
        
        private bool meetingCodeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long acceptTimer {
            get {
                return this.acceptTimerField;
            }
            set {
                this.acceptTimerField = value;
                this.RaisePropertyChanged("acceptTimer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool acceptTimerSpecified {
            get {
                return this.acceptTimerFieldSpecified;
            }
            set {
                this.acceptTimerFieldSpecified = value;
                this.RaisePropertyChanged("acceptTimerSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double accountBalance {
            get {
                return this.accountBalanceField;
            }
            set {
                this.accountBalanceField = value;
                this.RaisePropertyChanged("accountBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accountBalanceSpecified {
            get {
                return this.accountBalanceFieldSpecified;
            }
            set {
                this.accountBalanceFieldSpecified = value;
                this.RaisePropertyChanged("accountBalanceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string allUpFormula {
            get {
                return this.allUpFormulaField;
            }
            set {
                this.allUpFormulaField = value;
                this.RaisePropertyChanged("allUpFormula");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double amountCreditBalance {
            get {
                return this.amountCreditBalanceField;
            }
            set {
                this.amountCreditBalanceField = value;
                this.RaisePropertyChanged("amountCreditBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountCreditBalanceSpecified {
            get {
                return this.amountCreditBalanceFieldSpecified;
            }
            set {
                this.amountCreditBalanceFieldSpecified = value;
                this.RaisePropertyChanged("amountCreditBalanceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("amountInvestedList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public System.Nullable<double>[] amountInvestedList {
            get {
                return this.amountInvestedListField;
            }
            set {
                this.amountInvestedListField = value;
                this.RaisePropertyChanged("amountInvestedList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double amountSessionBalance {
            get {
                return this.amountSessionBalanceField;
            }
            set {
                this.amountSessionBalanceField = value;
                this.RaisePropertyChanged("amountSessionBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountSessionBalanceSpecified {
            get {
                return this.amountSessionBalanceFieldSpecified;
            }
            set {
                this.amountSessionBalanceFieldSpecified = value;
                this.RaisePropertyChanged("amountSessionBalanceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double amountTicket {
            get {
                return this.amountTicketField;
            }
            set {
                this.amountTicketField = value;
                this.RaisePropertyChanged("amountTicket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool amountTicketSpecified {
            get {
                return this.amountTicketFieldSpecified;
            }
            set {
                this.amountTicketFieldSpecified = value;
                this.RaisePropertyChanged("amountTicketSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double amountWithdraw {
            get {
                return this.amountWithdrawField;
            }
            set {
                this.amountWithdrawField = value;
                this.RaisePropertyChanged("amountWithdraw");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double betCostAmount {
            get {
                return this.betCostAmountField;
            }
            set {
                this.betCostAmountField = value;
                this.RaisePropertyChanged("betCostAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool betCostAmountSpecified {
            get {
                return this.betCostAmountFieldSpecified;
            }
            set {
                this.betCostAmountFieldSpecified = value;
                this.RaisePropertyChanged("betCostAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public long betRefId {
            get {
                return this.betRefIdField;
            }
            set {
                this.betRefIdField = value;
                this.RaisePropertyChanged("betRefId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public System.DateTime betSoldTime {
            get {
                return this.betSoldTimeField;
            }
            set {
                this.betSoldTimeField = value;
                this.RaisePropertyChanged("betSoldTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool betSoldTimeSpecified {
            get {
                return this.betSoldTimeFieldSpecified;
            }
            set {
                this.betSoldTimeFieldSpecified = value;
                this.RaisePropertyChanged("betSoldTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("comboBetContent", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=11)]
        public comboBetContent[] comboBetContent {
            get {
                return this.comboBetContentField;
            }
            set {
                this.comboBetContentField = value;
                this.RaisePropertyChanged("comboBetContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int scheduledType {
            get {
                return this.scheduledTypeField;
            }
            set {
                this.scheduledTypeField = value;
                this.RaisePropertyChanged("scheduledType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string counterOfferPayout {
            get {
                return this.counterOfferPayoutField;
            }
            set {
                this.counterOfferPayoutField = value;
                this.RaisePropertyChanged("counterOfferPayout");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string counterOfferReturn {
            get {
                return this.counterOfferReturnField;
            }
            set {
                this.counterOfferReturnField = value;
                this.RaisePropertyChanged("counterOfferReturn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string counterOfferTake {
            get {
                return this.counterOfferTakeField;
            }
            set {
                this.counterOfferTakeField = value;
                this.RaisePropertyChanged("counterOfferTake");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deductDetailsList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=16)]
        public deductDetailsResp[] deductDetailsList {
            get {
                return this.deductDetailsListField;
            }
            set {
                this.deductDetailsListField = value;
                this.RaisePropertyChanged("deductDetailsList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public bool flexiBet {
            get {
                return this.flexiBetField;
            }
            set {
                this.flexiBetField = value;
                this.RaisePropertyChanged("flexiBet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("flexiList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=18)]
        public flexiResp[] flexiList {
            get {
                return this.flexiListField;
            }
            set {
                this.flexiListField = value;
                this.RaisePropertyChanged("flexiList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("legList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=19)]
        public legDetailsResp[] legList {
            get {
                return this.legListField;
            }
            set {
                this.legListField = value;
                this.RaisePropertyChanged("legList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public System.DateTime meetingDate {
            get {
                return this.meetingDateField;
            }
            set {
                this.meetingDateField = value;
                this.RaisePropertyChanged("meetingDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool meetingDateSpecified {
            get {
                return this.meetingDateFieldSpecified;
            }
            set {
                this.meetingDateFieldSpecified = value;
                this.RaisePropertyChanged("meetingDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string meetingLocation {
            get {
                return this.meetingLocationField;
            }
            set {
                this.meetingLocationField = value;
                this.RaisePropertyChanged("meetingLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string meetingName {
            get {
                return this.meetingNameField;
            }
            set {
                this.meetingNameField = value;
                this.RaisePropertyChanged("meetingName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("multiParlayContentList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=23)]
        public multiParlayContent[] multiParlayContentList {
            get {
                return this.multiParlayContentListField;
            }
            set {
                this.multiParlayContentListField = value;
                this.RaisePropertyChanged("multiParlayContentList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public bool mystery {
            get {
                return this.mysteryField;
            }
            set {
                this.mysteryField = value;
                this.RaisePropertyChanged("mystery");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public double openBalance {
            get {
                return this.openBalanceField;
            }
            set {
                this.openBalanceField = value;
                this.RaisePropertyChanged("openBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool openBalanceSpecified {
            get {
                return this.openBalanceFieldSpecified;
            }
            set {
                this.openBalanceFieldSpecified = value;
                this.RaisePropertyChanged("openBalanceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string overAllPayout {
            get {
                return this.overAllPayoutField;
            }
            set {
                this.overAllPayoutField = value;
                this.RaisePropertyChanged("overAllPayout");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public int overallStatus {
            get {
                return this.overallStatusField;
            }
            set {
                this.overallStatusField = value;
                this.RaisePropertyChanged("overallStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public int promotionFlag {
            get {
                return this.promotionFlagField;
            }
            set {
                this.promotionFlagField = value;
                this.RaisePropertyChanged("promotionFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string returnsOverall {
            get {
                return this.returnsOverallField;
            }
            set {
                this.returnsOverallField = value;
                this.RaisePropertyChanged("returnsOverall");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string statusMessage {
            get {
                return this.statusMessageField;
            }
            set {
                this.statusMessageField = value;
                this.RaisePropertyChanged("statusMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string statusType {
            get {
                return this.statusTypeField;
            }
            set {
                this.statusTypeField = value;
                this.RaisePropertyChanged("statusType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string transactionNumber {
            get {
                return this.transactionNumberField;
            }
            set {
                this.transactionNumberField = value;
                this.RaisePropertyChanged("transactionNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public int meetingCode {
            get {
                return this.meetingCodeField;
            }
            set {
                this.meetingCodeField = value;
                this.RaisePropertyChanged("meetingCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool meetingCodeSpecified {
            get {
                return this.meetingCodeFieldSpecified;
            }
            set {
                this.meetingCodeFieldSpecified = value;
                this.RaisePropertyChanged("meetingCodeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/")]
    public partial class bettingResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long accountIdField;
        
        private bool accountIdFieldSpecified;
        
        private betDetailsResp[] betDetailsResponseListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long accountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
                this.RaisePropertyChanged("accountId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accountIdSpecified {
            get {
                return this.accountIdFieldSpecified;
            }
            set {
                this.accountIdFieldSpecified = value;
                this.RaisePropertyChanged("accountIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("betDetailsResponseList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public betDetailsResp[] betDetailsResponseList {
            get {
                return this.betDetailsResponseListField;
            }
            set {
                this.betDetailsResponseListField = value;
                this.RaisePropertyChanged("betDetailsResponseList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/")]
    public partial class legDetailsReq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int prodCodeField;
        
        private long propositionNumberField;
        
        private int raceNumberField;
        
        private betSelection[] selectionListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int prodCode {
            get {
                return this.prodCodeField;
            }
            set {
                this.prodCodeField = value;
                this.RaisePropertyChanged("prodCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long propositionNumber {
            get {
                return this.propositionNumberField;
            }
            set {
                this.propositionNumberField = value;
                this.RaisePropertyChanged("propositionNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int raceNumber {
            get {
                return this.raceNumberField;
            }
            set {
                this.raceNumberField = value;
                this.RaisePropertyChanged("raceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("selectionList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public betSelection[] selectionList {
            get {
                return this.selectionListField;
            }
            set {
                this.selectionListField = value;
                this.RaisePropertyChanged("selectionList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/")]
    public partial class betAmount : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double amountInvestedField;
        
        private string returnsPerBetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double amountInvested {
            get {
                return this.amountInvestedField;
            }
            set {
                this.amountInvestedField = value;
                this.RaisePropertyChanged("amountInvested");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string returnsPerBet {
            get {
                return this.returnsPerBetField;
            }
            set {
                this.returnsPerBetField = value;
                this.RaisePropertyChanged("returnsPerBet");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/")]
    public partial class betDetailsReq : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int acceptPartialField;
        
        private bool accumulatorBetField;
        
        private short accumulatorIdField;
        
        private string allUpFormulaField;
        
        private betAmount[] betAmountListField;
        
        private long betRefIdField;
        
        private string betTypeField;
        
        private int scheduledTypeField;
        
        private int fixedOddsProdCodeField;
        
        private bool flexiBetField;
        
        private legDetailsReq[] legListField;
        
        private System.DateTime meetingDateField;
        
        private bool meetingDateFieldSpecified;
        
        private string multiParlayFormulaField;
        
        private bool mysteryField;
        
        private int notifyMethodField;
        
        private int numMultiParlayBetField;
        
        private long ordinalNumberField;
        
        private int meetingCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int acceptPartial {
            get {
                return this.acceptPartialField;
            }
            set {
                this.acceptPartialField = value;
                this.RaisePropertyChanged("acceptPartial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool accumulatorBet {
            get {
                return this.accumulatorBetField;
            }
            set {
                this.accumulatorBetField = value;
                this.RaisePropertyChanged("accumulatorBet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public short accumulatorId {
            get {
                return this.accumulatorIdField;
            }
            set {
                this.accumulatorIdField = value;
                this.RaisePropertyChanged("accumulatorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string allUpFormula {
            get {
                return this.allUpFormulaField;
            }
            set {
                this.allUpFormulaField = value;
                this.RaisePropertyChanged("allUpFormula");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("betAmountList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public betAmount[] betAmountList {
            get {
                return this.betAmountListField;
            }
            set {
                this.betAmountListField = value;
                this.RaisePropertyChanged("betAmountList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long betRefId {
            get {
                return this.betRefIdField;
            }
            set {
                this.betRefIdField = value;
                this.RaisePropertyChanged("betRefId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string betType {
            get {
                return this.betTypeField;
            }
            set {
                this.betTypeField = value;
                this.RaisePropertyChanged("betType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int scheduledType {
            get {
                return this.scheduledTypeField;
            }
            set {
                this.scheduledTypeField = value;
                this.RaisePropertyChanged("scheduledType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int fixedOddsProdCode {
            get {
                return this.fixedOddsProdCodeField;
            }
            set {
                this.fixedOddsProdCodeField = value;
                this.RaisePropertyChanged("fixedOddsProdCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public bool flexiBet {
            get {
                return this.flexiBetField;
            }
            set {
                this.flexiBetField = value;
                this.RaisePropertyChanged("flexiBet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("legList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=10)]
        public legDetailsReq[] legList {
            get {
                return this.legListField;
            }
            set {
                this.legListField = value;
                this.RaisePropertyChanged("legList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public System.DateTime meetingDate {
            get {
                return this.meetingDateField;
            }
            set {
                this.meetingDateField = value;
                this.RaisePropertyChanged("meetingDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool meetingDateSpecified {
            get {
                return this.meetingDateFieldSpecified;
            }
            set {
                this.meetingDateFieldSpecified = value;
                this.RaisePropertyChanged("meetingDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string multiParlayFormula {
            get {
                return this.multiParlayFormulaField;
            }
            set {
                this.multiParlayFormulaField = value;
                this.RaisePropertyChanged("multiParlayFormula");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public bool mystery {
            get {
                return this.mysteryField;
            }
            set {
                this.mysteryField = value;
                this.RaisePropertyChanged("mystery");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int notifyMethod {
            get {
                return this.notifyMethodField;
            }
            set {
                this.notifyMethodField = value;
                this.RaisePropertyChanged("notifyMethod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public int numMultiParlayBet {
            get {
                return this.numMultiParlayBetField;
            }
            set {
                this.numMultiParlayBetField = value;
                this.RaisePropertyChanged("numMultiParlayBet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public long ordinalNumber {
            get {
                return this.ordinalNumberField;
            }
            set {
                this.ordinalNumberField = value;
                this.RaisePropertyChanged("ordinalNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public int meetingCode {
            get {
                return this.meetingCodeField;
            }
            set {
                this.meetingCodeField = value;
                this.RaisePropertyChanged("meetingCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/")]
    public partial class bettingRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long accountPinField;
        
        private betDetailsReq[] betDetailsRequestListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long accountPin {
            get {
                return this.accountPinField;
            }
            set {
                this.accountPinField = value;
                this.RaisePropertyChanged("accountPin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("betDetailsRequestList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public betDetailsReq[] betDetailsRequestList {
            get {
                return this.betDetailsRequestListField;
            }
            set {
                this.betDetailsRequestListField = value;
                this.RaisePropertyChanged("betDetailsRequestList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/")]
    public partial class apiMeta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long deviceIdField;
        
        private bool deviceIdFieldSpecified;
        
        private long jurisdictionIdField;
        
        private long requestChannelField;
        
        private bool requestChannelFieldSpecified;
        
        private string usernamePasswordTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long deviceId {
            get {
                return this.deviceIdField;
            }
            set {
                this.deviceIdField = value;
                this.RaisePropertyChanged("deviceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deviceIdSpecified {
            get {
                return this.deviceIdFieldSpecified;
            }
            set {
                this.deviceIdFieldSpecified = value;
                this.RaisePropertyChanged("deviceIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long jurisdictionId {
            get {
                return this.jurisdictionIdField;
            }
            set {
                this.jurisdictionIdField = value;
                this.RaisePropertyChanged("jurisdictionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long requestChannel {
            get {
                return this.requestChannelField;
            }
            set {
                this.requestChannelField = value;
                this.RaisePropertyChanged("requestChannel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requestChannelSpecified {
            get {
                return this.requestChannelFieldSpecified;
            }
            set {
                this.requestChannelFieldSpecified = value;
                this.RaisePropertyChanged("requestChannelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string usernamePasswordToken {
            get {
                return this.usernamePasswordTokenField;
            }
            set {
                this.usernamePasswordTokenField = value;
                this.RaisePropertyChanged("usernamePasswordToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/", ConfigurationName="wsTabBetting.BettingService")]
    public interface BettingService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TheMinx.wsTabBetting.APIException), Action="", Name="APIException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TheMinx.wsTabBetting.validateBetResponse validateBet(TheMinx.wsTabBetting.validateBet request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TheMinx.wsTabBetting.validateBetResponse> validateBetAsync(TheMinx.wsTabBetting.validateBet request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TheMinx.wsTabBetting.APIException), Action="", Name="APIException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TheMinx.wsTabBetting.placeBetResponse placeBet(TheMinx.wsTabBetting.placeBet request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<TheMinx.wsTabBetting.placeBetResponse> placeBetAsync(TheMinx.wsTabBetting.placeBet request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateBet", WrapperNamespace="http://service.betting.api.neo.tabcorp.com.au/", IsWrapped=true)]
    public partial class validateBet {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TheMinx.wsTabBetting.apiMeta apiMeta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TheMinx.wsTabBetting.bettingRequest bettingRequest;
        
        public validateBet() {
        }
        
        public validateBet(TheMinx.wsTabBetting.apiMeta apiMeta, TheMinx.wsTabBetting.bettingRequest bettingRequest) {
            this.apiMeta = apiMeta;
            this.bettingRequest = bettingRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validateBetResponse", WrapperNamespace="http://service.betting.api.neo.tabcorp.com.au/", IsWrapped=true)]
    public partial class validateBetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TheMinx.wsTabBetting.bettingResponse @return;
        
        public validateBetResponse() {
        }
        
        public validateBetResponse(TheMinx.wsTabBetting.bettingResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="placeBet", WrapperNamespace="http://service.betting.api.neo.tabcorp.com.au/", IsWrapped=true)]
    public partial class placeBet {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TheMinx.wsTabBetting.apiMeta apiMeta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TheMinx.wsTabBetting.bettingRequest bettingRequest;
        
        public placeBet() {
        }
        
        public placeBet(TheMinx.wsTabBetting.apiMeta apiMeta, TheMinx.wsTabBetting.bettingRequest bettingRequest) {
            this.apiMeta = apiMeta;
            this.bettingRequest = bettingRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="placeBetResponse", WrapperNamespace="http://service.betting.api.neo.tabcorp.com.au/", IsWrapped=true)]
    public partial class placeBetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://service.betting.api.neo.tabcorp.com.au/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TheMinx.wsTabBetting.bettingResponse @return;
        
        public placeBetResponse() {
        }
        
        public placeBetResponse(TheMinx.wsTabBetting.bettingResponse @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BettingServiceChannel : TheMinx.wsTabBetting.BettingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BettingServiceClient : System.ServiceModel.ClientBase<TheMinx.wsTabBetting.BettingService>, TheMinx.wsTabBetting.BettingService {
        
        public BettingServiceClient() {
        }
        
        public BettingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BettingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BettingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BettingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TheMinx.wsTabBetting.validateBetResponse TheMinx.wsTabBetting.BettingService.validateBet(TheMinx.wsTabBetting.validateBet request) {
            return base.Channel.validateBet(request);
        }
        
        public TheMinx.wsTabBetting.bettingResponse validateBet(TheMinx.wsTabBetting.apiMeta apiMeta, TheMinx.wsTabBetting.bettingRequest bettingRequest) {
            TheMinx.wsTabBetting.validateBet inValue = new TheMinx.wsTabBetting.validateBet();
            inValue.apiMeta = apiMeta;
            inValue.bettingRequest = bettingRequest;
            TheMinx.wsTabBetting.validateBetResponse retVal = ((TheMinx.wsTabBetting.BettingService)(this)).validateBet(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TheMinx.wsTabBetting.validateBetResponse> TheMinx.wsTabBetting.BettingService.validateBetAsync(TheMinx.wsTabBetting.validateBet request) {
            return base.Channel.validateBetAsync(request);
        }
        
        public System.Threading.Tasks.Task<TheMinx.wsTabBetting.validateBetResponse> validateBetAsync(TheMinx.wsTabBetting.apiMeta apiMeta, TheMinx.wsTabBetting.bettingRequest bettingRequest) {
            TheMinx.wsTabBetting.validateBet inValue = new TheMinx.wsTabBetting.validateBet();
            inValue.apiMeta = apiMeta;
            inValue.bettingRequest = bettingRequest;
            return ((TheMinx.wsTabBetting.BettingService)(this)).validateBetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TheMinx.wsTabBetting.placeBetResponse TheMinx.wsTabBetting.BettingService.placeBet(TheMinx.wsTabBetting.placeBet request) {
            return base.Channel.placeBet(request);
        }
        
        public TheMinx.wsTabBetting.bettingResponse placeBet(TheMinx.wsTabBetting.apiMeta apiMeta, TheMinx.wsTabBetting.bettingRequest bettingRequest) {
            TheMinx.wsTabBetting.placeBet inValue = new TheMinx.wsTabBetting.placeBet();
            inValue.apiMeta = apiMeta;
            inValue.bettingRequest = bettingRequest;
            TheMinx.wsTabBetting.placeBetResponse retVal = ((TheMinx.wsTabBetting.BettingService)(this)).placeBet(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TheMinx.wsTabBetting.placeBetResponse> TheMinx.wsTabBetting.BettingService.placeBetAsync(TheMinx.wsTabBetting.placeBet request) {
            return base.Channel.placeBetAsync(request);
        }
        
        public System.Threading.Tasks.Task<TheMinx.wsTabBetting.placeBetResponse> placeBetAsync(TheMinx.wsTabBetting.apiMeta apiMeta, TheMinx.wsTabBetting.bettingRequest bettingRequest) {
            TheMinx.wsTabBetting.placeBet inValue = new TheMinx.wsTabBetting.placeBet();
            inValue.apiMeta = apiMeta;
            inValue.bettingRequest = bettingRequest;
            return ((TheMinx.wsTabBetting.BettingService)(this)).placeBetAsync(inValue);
        }
    }
}
